# Generated by Django 5.1.2 on 2024-11-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Article', 'Article'), ('Component', 'Component')], default='Article', max_length=10, null=True),
        ),
    ]
