# Generated by Django 5.1.2 on 2024-11-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Link this component to an article product.', limit_choices_to={'product_type': 'Article'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.product'),
        ),
    ]
