# Generated by Django 5.1.2 on 2024-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_linked_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_product_category',
            field=models.CharField(blank=True, help_text="Specify custom product category if 'Other' is selected.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Table', 'Table'), ('Capsule', 'Capsule'), ('Powder', 'Powder'), ('Liquid', 'Liquid'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
    ]
