# Generated by Django 5.1.2 on 2024-11-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_custom_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Table', 'Tablet'), ('Capsule', 'Capsule'), ('Powder', 'Powder'), ('Liquid', 'Liquid'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
    ]
