# Generated by Django 5.1.2 on 2024-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
