# Generated by Django 5.1.2 on 2024-12-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_product_custom_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content_types', models.JSONField(default=list, help_text="A list of content types this container can hold (e.g., ['Liquid', 'Cream']).")),
                ('allowed_uoms', models.JSONField(default=dict, help_text="A dictionary mapping content types to their allowed UOMs (e.g., {'Liquid': ['ml', 'liters']}).")),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, help_text='The container used to hold this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.container'),
        ),
    ]
