# Generated by Django 5.1.2 on 2024-12-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_container_product_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Pack', 'Pack'), ('Box', 'Box'), ('Bag', 'Bag')], help_text='Select a container type.', max_length=50, unique=True),
        ),
    ]
