# Generated by Django 5.1.2 on 2024-12-09 00:45

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='allowed_uoms',
            field=models.JSONField(default=inventory.models.default_allowed_uoms, help_text="A dictionary mapping content types to their allowed UOMs (e.g., {'Liquid': ['ml', 'liters']})."),
        ),
    ]
