# Generated by Django 5.1.2 on 2024-12-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_container_allowed_uoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of pieces per single container (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_type',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Powder', 'Powder'), ('Liquid', 'Liquid'), ('Syrup', 'Syrup'), ('Cream', 'Cream'), ('Leaves', 'Leaves'), ('Oil', 'Oil'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
    ]
