# Generated by Django 5.1.2 on 2024-12-09 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_pieces_per_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='allowed_uoms',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='container',
            name='content_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='linked_article',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'Article'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_article',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
