# Generated by Django 5.1.2 on 2024-12-09 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_container_allowed_uoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='allowed_uoms',
            field=models.JSONField(default=dict, help_text='A dictionary mapping content types to their allowed UOMs.'),
        ),
        migrations.AlterField(
            model_name='container',
            name='content_types',
            field=models.JSONField(default=list, help_text="A list of content types this container can hold (e.g., ['Liquid', 'Cream'])."),
        ),
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, help_text='The container used to hold this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_content_type',
            field=models.CharField(blank=True, help_text="Specify custom content type if 'Other' is selected.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Link this component to an article product.', limit_choices_to={'product_type': 'Article'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of pieces per single container (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_article',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of units of this component required to create one article.', null=True),
        ),
    ]
