# Generated by Django 5.1.2 on 2024-12-09 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_container_allowed_uoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Link this component to an Article product.', limit_choices_to={'product_type': 'Article'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of pieces per single container (for Articles). For Components, this is typically not used.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='For Articles, this is the number of containers. For Components, this is the count of pieces/units.', null=True),
        ),
    ]
