# Generated by Django 5.1.2 on 2024-12-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_product_linked_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='content_types',
            field=models.JSONField(default=list, help_text='A list of content types this container can hold.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='For Articles: number of pieces per container.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='For Articles: number of containers. For Components: number of pieces.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_article',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='For Components: How many units are needed per article.', null=True),
        ),
    ]
