# Generated by Django 5.1.2 on 2024-12-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_container_content_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='content_types',
            field=models.JSONField(default=list, help_text="A list of content types this container can hold (e.g., ['Liquid', 'Cream'])."),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_per_container',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of pieces per single container (for Articles). For Components, this is typically not used.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='For Articles, this is the number of containers. For Components, this is the count of pieces/units.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_article',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of units of this component required to create one article.', null=True),
        ),
    ]
