# Generated by Django 5.1.2 on 2024-11-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patients_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(default='TXNBA8E5129', max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('issuer', models.CharField(default='JOHNTANG', max_length=255)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('address', models.TextField(editable=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='patients.patients')),
            ],
        ),
    ]
