# Generated by Django 5.1.2 on 2024-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
