# Generated by Django 5.1.2 on 2024-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issuer',
            field=models.CharField(default='Sebastian Liew', max_length=255),
        ),
    ]
