# Generated by Django 5.1.2 on 2024-12-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('nric_passport', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_contactable', models.BooleanField(default=False)),
                ('referral_source', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced / Widowed')], max_length=20)),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True)),
                ('normal_delivery', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('drink_alcohol', models.CharField(choices=[('less_than_3', 'Yes, less than 3 times per week'), ('more_than_3', 'Yes, more than 3 times per week'), ('no', 'No')], max_length=20)),
                ('special_diet', models.CharField(blank=True, max_length=100, null=True)),
                ('current_conditions', models.CharField(blank=True, max_length=50, null=True)),
                ('medications_supplements', models.TextField()),
                ('symptoms_onset', models.CharField(blank=True, max_length=255, null=True)),
                ('provoked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('better_with', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom_severity', models.PositiveSmallIntegerField(blank=True, help_text='Severity from 1 - 10', null=True)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('digestion', models.CharField(blank=True, max_length=255, null=True)),
                ('menstrual_health', models.CharField(blank=True, max_length=255, null=True)),
                ('heart_health', models.CharField(blank=True, max_length=255, null=True)),
                ('nervous_system', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('past_surgery', models.TextField(blank=True, null=True)),
                ('immune_health', models.CharField(blank=True, max_length=255, null=True)),
                ('thyroid', models.CharField(blank=True, max_length=255, null=True)),
                ('energy_level', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_health', models.CharField(blank=True, max_length=255, null=True)),
                ('prepares_meals', models.BooleanField(default=False)),
                ('skips_breakfast', models.BooleanField(default=False)),
                ('breakfast_description', models.TextField(blank=True, null=True)),
                ('vegan', models.BooleanField(default=False)),
                ('daily_beverage', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_favorite_food', models.CharField(blank=True, max_length=255, null=True)),
                ('join_mailing_list', models.BooleanField(default=False)),
                ('pdpa_consent', models.BooleanField(default=False)),
                ('informed_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
