# Generated by Django 5.1.2 on 2024-12-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patient_no',
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.TextField(blank=True, default='No address provided', null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='country',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, default='unknown@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='fax',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='first_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='nric',
            field=models.CharField(default='UNKNOWN-NRIC', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks', null=True),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt', models.CharField(blank=True, default='Not specified', max_length=50, null=True)),
                ('summary', models.TextField(blank=True, default='No summary provided', null=True)),
                ('instructions', models.TextField(blank=True, default='No instructions', null=True)),
                ('lifestyle', models.TextField(blank=True, default='No lifestyle details', null=True)),
                ('next_apt', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnosis_images/')),
                ('medication_status', models.CharField(choices=[('Issued', 'Issued'), ('Invoiced', 'Invoiced')], default='Invoiced', max_length=50)),
                ('diagnosis_date', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patients')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosis_date', '-created'],
            },
        ),
    ]
