# Generated by Django 5.1.2 on 2024-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patients_patient_no_alter_patients_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
